%V10_MAKETIKZ  Module V10.2: emit self-contained TikZ/pgfplots figures.
%
%   Writes three .tex figure bodies into ../figures/tikz/, each a
%   standalone tikzpicture usable via \input.  No external renderer
%   is needed: the figures compile with the manuscript.  Data are the
%   measured table values (log-loss) and errprob_data.mat (0-1 loss).

clear all; more off;
figdir = '../figures/tikz';
if ~exist(figdir, 'dir'), mkdir(figdir); end
if exist('errprob_data.mat', 'file')
  load('errprob_data.mat');          % Erec, Crec, written by v10_errprob
else
  % measured values from Module V10.1, so that this script can also be
  % run on its own without first repeating the sweep
  Crec = [ 1000 0.0189 0.0089
           2000 0.0176 0.0055
           4000 0.0184 0.0052
           8000 0.0208 0.0064
          16000 0.0198 0.0046];
end

ns    = [1000 2000 4000 8000 16000];
logn  = log(ns);
H035  = 1.0320;
bstar = [0.714 0.729 0.747 0.760 0.776];
exc_or  = [0.1464 0.1074 0.1201 0.1098 0.0855];
exc_slf = [0.0926 0.0558 0.0739 0.0612 0.0356];

  function s = coords(x, y)
    s = '';
    for i = 1:numel(x)
      s = [s sprintf('(%.5g,%.5g) ', x(i), y(i))];
    end
  end

% ============ Figure 1: approach to criticality ============
fid = fopen(fullfile(figdir,'fig_approach.tex'), 'w');
fprintf(fid, '%% auto-generated by v10_maketikz.m -- do not edit by hand\n');
fprintf(fid, '\\begin{tikzpicture}\n');
fprintf(fid, '\\begin{axis}[name=ax1,width=\\linewidth,height=4.2cm,\n');
fprintf(fid, '  xlabel={$\\log n$},ylabel={$\\beta^\\star(n)$},\n');
fprintf(fid, '  xtick={6.9,7.6,8.3,9,9.7},ymin=0.68,ymax=1.06,\n');
fprintf(fid, '  legend pos=north west,legend cell align=left,\n');
fprintf(fid, '  every axis plot/.append style={thick}]\n');
fprintf(fid, '\\addplot[mark=*,blue!70!black] coordinates {%s};\n', coords(logn,bstar));
fprintf(fid, '\\addplot[black,dashed,no marks] coordinates {(6.7,%.4f)(9.9,%.4f)};\n', H035, H035);
fprintf(fid, '\\legend{measured,$H$}\n');
fprintf(fid, '\\end{axis}\n');
fprintf(fid, '\\begin{axis}[name=ax2,at={(ax1.below south west)},anchor=above north west,yshift=-1.0cm,\n');
fprintf(fid, '  width=\\linewidth,height=4.2cm,\n');
fprintf(fid, '  xlabel={$1/\\log n$},ylabel={excess (nats)},\n');
fprintf(fid, '  legend pos=north west,legend cell align=left,\n');
fprintf(fid, '  every axis plot/.append style={thick}]\n');
fprintf(fid, '\\addplot[mark=square*,red!70!black] coordinates {%s};\n', coords(1./logn, exc_or));
c = exc_or(end)*logn(end);
fprintf(fid, '\\addplot[black,dotted,no marks] coordinates {%s};\n', coords(1./logn, c./logn));
fprintf(fid, '\\legend{oracle,$\\propto 1/\\log n$}\n');
fprintf(fid, '\\end{axis}\n\\end{tikzpicture}\n');
fclose(fid);

% ============ Figure 2: two-sided separation (log-log) ============
fid = fopen(fullfile(figdir,'fig_separation.tex'), 'w');
fprintf(fid, '%% auto-generated by v10_maketikz.m\n');
fprintf(fid, '\\begin{tikzpicture}\n');
fprintf(fid, '\\begin{loglogaxis}[width=\\linewidth,height=6.2cm,\n');
fprintf(fid, '  xlabel={$\\log n$},ylabel={excess log-loss (nats)},\n');
fprintf(fid, '  legend pos=south west,legend cell align=left,\n');
fprintf(fid, '  xtick={6.9,8.3,9.7},xticklabels={6.9,8.3,9.7},\n');
fprintf(fid, '  every axis plot/.append style={thick}]\n');
fprintf(fid, '\\addplot[mark=square*,red!70!black] coordinates {%s};\n', coords(logn, exc_or));
fprintf(fid, '\\addplot[mark=*,blue!70!black] coordinates {%s};\n', coords(logn, exc_slf));
c1 = exc_or(1)*sqrt(logn(1));
c2 = exc_slf(1)*logn(1);
fprintf(fid, '\\addplot[black,dashed,no marks] coordinates {%s};\n', coords(logn, c1./sqrt(logn)));
fprintf(fid, '\\addplot[black,dotted,no marks] coordinates {%s};\n', coords(logn, c2./logn));
fprintf(fid, '\\legend{fixed $\\beta^\\star(n)$,self-critical,$c/\\sqrt{\\log n}$,$c/\\log n$}\n');
fprintf(fid, '\\end{loglogaxis}\n\\end{tikzpicture}\n');
fclose(fid);

% ============ Figure 3: error-probability ============
fid = fopen(fullfile(figdir,'fig_errprob.tex'), 'w');
fprintf(fid, '%% auto-generated by v10_maketikz.m\n');
fprintf(fid, '\\begin{tikzpicture}\n');
fprintf(fid, '\\begin{semilogxaxis}[name=bx1,width=\\linewidth,height=4.2cm,\n');
fprintf(fid, '  xlabel={$n$},ylabel={excess error prob.},ymin=0,ymax=0.025,\n');
fprintf(fid, '  legend pos=north east,legend cell align=left,\n');
fprintf(fid, '  every axis plot/.append style={thick}]\n');
fprintf(fid, '\\addplot[mark=square*,red!70!black] coordinates {%s};\n', coords(Crec(:,1), Crec(:,2)));
fprintf(fid, '\\addplot[mark=*,blue!70!black] coordinates {%s};\n', coords(Crec(:,1), Crec(:,3)));
fprintf(fid, '\\legend{fixed $\\beta^\\star(n)$,self-critical}\n');
fprintf(fid, '\\end{semilogxaxis}\n');
fprintf(fid, '\\begin{semilogxaxis}[name=bx2,at={(bx1.below south west)},anchor=above north west,yshift=-1.0cm,\n');
fprintf(fid, '  width=\\linewidth,height=4.2cm,\n');
fprintf(fid, '  xlabel={$n$},ylabel={adaptivity ratio},\n');
fprintf(fid, '  legend pos=north west,legend cell align=left,\n');
fprintf(fid, '  every axis plot/.append style={thick}]\n');
r01 = Crec(:,2)./max(Crec(:,3),1e-6);
rll = exc_or(:)./exc_slf(:);
fprintf(fid, '\\addplot[mark=diamond*,green!45!black] coordinates {%s};\n', coords(Crec(:,1), r01));
fprintf(fid, '\\addplot[mark=triangle*,violet!70!black] coordinates {%s};\n', coords(ns, rll));
fprintf(fid, '\\legend{0--1 loss,log-loss}\n');
fprintf(fid, '\\end{semilogxaxis}\n\\end{tikzpicture}\n');
fclose(fid);

fprintf('[V10.2] wrote fig_approach.tex, fig_separation.tex, fig_errprob.tex\n');
fprintf('  0-1 ratio:  ');  fprintf('%.2f ', Crec(:,2)./max(Crec(:,3),1e-6));  fprintf('\n');
fprintf('  ll ratio:   ');  fprintf('%.2f ', exc_or(:)./exc_slf(:));  fprintf('\n');
